### ISSUE TITLE
Refresh Token Workflow

### ISSUE THREAD

**Issue by taddeimania** [Wapaca/livecoding-auth#4]
Hey @Wapaca & @bill-auger , I wanted to provide my insight into how I was able to get the refresh token auth working so that users can continually retain an API integration without having to manually reauthorize with lctv. I'll just go through the whole lifecycle of a token and a user on my site.

Glossary (just to make sure we're all using the same terms):
**Access Code**: The code given to the redirect_url after a user has authorized with lctv
**Token Endpoint**: The lctv API endpoint you post to retrieve your access/refresh tokens.
**Access Token**: The authorization token that goes in the header for every API request ("Authorization: Bearer asdlknasdlasdla98bb")
**Refresh Token**: an additional token you retrieve when you post to the token endpoint. This token is used to get new access and refresh tokens.

### Scenario 1: Signing up for lctv analytics
When a user signs in to lctv analytics with their username and password they are not linked to lctv by default. I make them click a "link" button.  This button redirects them to the authorize endpoint on lctv and they have to click "authorize".  LCTV then redirects them back to my postback url where I capture all of the relevant data and put it into a database record tied to the user. Relevant data being `access code`, `access token`, `refresh token`, and `user`.

After they have authorized I store their lctv username (retrieved through an API call on the backend) on their local user account to tie them to the analytics records.

Request headers for a typical API request look like this:

```
            'authorization': "Bearer ACCESS_TOKEN",
            'cache-control': "no-cache",
```

This should be enough given a typical `GET` request to an API endpoint you have permission to use based on your scope.

### Scenario 2: Access Token expires
For every API request I make for a user I check the returning status code. If it is a `401` I go down my `refresh_token` workflow.

To refresh a token I have to go to the database to find their existing token in the database (typically using their username to look it up), that will give me their `access_code` and their `refresh_token`. At this point the `access_token` is void and we can ignore it.

For a new token you need to post to the same endpoint (`https://www.livecoding.tv/o/token/`) but with a different payload.  The `POST` payload is structured like this:

```
code=ACCESS_CODE&grant_type=refresh_token&redirect_uri=REDIRECT_URL&client_id=CLIENT_ID&client_secret=CLIENT_SECRET&refresh_token=REFRESH_TOKEN
```

Assuming all of the codes are correct you should receive a response containing:

```{
  "access_token": NEW_ACCESS_TOKEN,
  "token_type": "Bearer",
  "expires_in": 36000,
  "refresh_token": NEW_REFRESH_TOKEN,
  "scope": "read"
}```

From there I take the new `access_token` and `refresh_token` and update my database record.  Then I take the new tokens and retry the API request.  So far my test scenarios have not failed.  It can take ~4 seconds for the refresh workflow to return actual requested API data, but it's very smooth.

Here is the client I wrote (in python) to abstract this away for my web app development.

https://github.com/taddeimania/lctva/blob/master/app/client.py

Hope this has helped!
@taddeimania

**Comment by Wapaca** [comment]
Hi taddeimania,

Thans for the help, i wasn't sure about the lifetime of the refresh token but apparently it's bigger than the access token's lifetime. 

I use a similar workflow on my bridge http://lctv.williambartolini.fr/ but i don't need the code (see this doc : http://tools.ietf.org/html/rfc6749#section-6 ) the code is only useful the create the first access token, not on refresh and i do the refresh minimum 5 hours after the creation of the last access token, not once it's expired.

I saw you message on lctv bill channel on the requests limit so yeah i will have to limit my users and do some workaround (like using more than 1 app for the website) if i get some users. Anyway thanks for your feedback.

**Comment by bill-auger** [comment]
i think what taddeimania is saying is that the cron task can be avoided but presenting the original auth code along with each refresh request

the cron task is perhaps reasonable for the purpose of your bridge because you are dealing with only one user token but for his app he would need to constantly refresh for every user - instead he can request new token per user only when needed

because the focus of this library is to abstract away the details of token negotiation then taddeimania's approach is probably more suitable for this project as not to require the library user to also setup a cron task

**Comment by Wapaca** [comment]
Taddeimania just shown me on his channel a test on the refresh token workflow and it works without passing the code, redirect url and etc...

You just have to send the refresh token, authorisation grant type to refresh token and your client_id/client_secret authorisation in the header.
